# Generated by Django 5.1.5 on 2026-09-22 19:15

import apps.profiles.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.profiles.models.cv_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('done', 'Terminé'), ('error', 'Erreur')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('extracted_text', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='titre')),
                ('summary', models.TextField(blank=True, verbose_name='résumé')),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True, verbose_name="années d'expérience")),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='ville')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='poste')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='entreprise')),
                ('start_date', models.CharField(blank=True, max_length=50, verbose_name='date de début')),
                ('end_date', models.CharField(blank=True, max_length=50, verbose_name='date de fin')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='profiles.profile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=255, verbose_name='diplôme')),
                ('institution', models.CharField(blank=True, max_length=255, verbose_name='établissement')),
                ('year', models.CharField(blank=True, max_length=20, verbose_name='année')),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='profiles.profile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('technical', 'Technique'), ('tool', 'Outil'), ('language', 'Langue'), ('soft_skill', 'Savoir-être')], max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='profiles.profile')),
            ],
            options={
                'ordering': ['category', 'display_name'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'normalized_name'), name='unique_skill_per_profile')],
            },
        ),
    ]
