# Generated by Django 5.1.5 on 2026-09-23 00:44

import apps.profiles.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_types', models.JSONField(default=apps.profiles.models._default_contract_types, verbose_name='types de contrat visés')),
                ('countries', models.JSONField(default=apps.profiles.models._default_countries, verbose_name='pays visés')),
                ('cities', models.JSONField(blank=True, default=list, verbose_name='villes visées')),
                ('remote_ok', models.BooleanField(default=True, verbose_name='télétravail accepté')),
                ('desired_duration_months', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='durée souhaitée (mois)')),
                ('desired_start_date', models.CharField(blank=True, max_length=100, verbose_name='date de début souhaitée')),
                ('languages', models.JSONField(blank=True, default=list, verbose_name='langues')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
