# Generated by Django 5.1.5 on 2026-09-22 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='titre')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='entreprise')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='lieu')),
                ('remote', models.BooleanField(default=False, verbose_name='télétravail')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='URL')),
                ('source', models.CharField(choices=[('remotive', 'Remotive'), ('arbeitnow', 'Arbeitnow'), ('manuel', 'Manuel')], max_length=20)),
                ('external_id', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='date de publication')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name="date d'import")),
                ('tags', models.JSONField(blank=True, default=list)),
                ('salary', models.CharField(blank=True, max_length=255, verbose_name='salaire')),
                ('language', models.CharField(blank=True, max_length=10, verbose_name='langue')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['published_at'], name='jobs_joboff_publish_ec5b01_idx'), models.Index(fields=['source'], name='jobs_joboff_source_b7b4ec_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_source_external_id')],
            },
        ),
    ]
