# Generated by Django 5.1.5 on 2026-09-23 00:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='contract_type',
            field=models.CharField(choices=[('stage', 'Stage'), ('alternance', 'Alternance'), ('cdi', 'CDI'), ('cdd', 'CDD'), ('freelance', 'Freelance'), ('inconnu', 'Inconnu')], default='inconnu', max_length=20, verbose_name='type de contrat'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='duration_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='durée (mois)'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='start_date',
            field=models.CharField(blank=True, max_length=100, verbose_name='date de début'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='source',
            field=models.CharField(choices=[('remotive', 'Remotive'), ('arbeitnow', 'Arbeitnow'), ('france_travail', 'France Travail'), ('manuel', 'Manuel')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='joboffer',
            index=models.Index(fields=['contract_type'], name='jobs_joboff_contrac_e4298c_idx'),
        ),
    ]
