# Generated by Django 5.1.5 on 2026-09-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_joboffer_contract_type_joboffer_duration_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='contract_type',
            field=models.CharField(choices=[('stage', 'Stage'), ('alternance', 'Alternance'), ('cdi', 'CDI'), ('cdd', 'CDD'), ('interim', 'Intérim'), ('freelance', 'Freelance'), ('inconnu', 'Inconnu')], default='inconnu', max_length=20, verbose_name='type de contrat'),
        ),
    ]
