# Generated by Django 5.1.5 on 2026-09-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='administrative_notes',
            field=models.JSONField(blank=True, default=list, verbose_name='admissibilité administrative'),
        ),
    ]
