# Generated by Django 5.1.5 on 2026-09-22 20:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='status_changed_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 22, 20, 58, 10, 800837, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('to_apply', 'À postuler'), ('sent', 'Envoyée'), ('interview', 'Entretien'), ('offer', 'Offre reçue'), ('rejected', 'Refus')], default='sent', max_length=20),
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('to_apply', 'À postuler'), ('sent', 'Envoyée'), ('interview', 'Entretien'), ('offer', 'Offre reçue'), ('rejected', 'Refus')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='applications.application')),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
    ]
